version: "3.8"

services:
  backend:
    container_name: backend
    working_dir: /app
    build:
      context: ./docker
      dockerfile: backend.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
      - app_network

  frontend:
    container_name: frontend
    working_dir: /app
    build:
      context: ./docker
      dockerfile: frontend.dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app_network

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: myapppassword
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    environment:
      - PARAMS=http -region=eu -authtoken=${NGROK_AUTH_TOKEN} localhost:3000
    networks:
      - app_network

volumes:
  postgres-data:

networks:
  app_network:
    driver: bridge
